title: Thoai Le Homepage
page-top-title: Thoai Le
top-section-bg-text: Computer Science
home-subtitle: Thoai Le
copyright-text: '&copy; <a href="https://github.com/senli1073/senli1073.github.io">Sen Li</a> 2023-2024. All Rights Reserved.'
