title: Thoai Le
nav-title: Thoai Le
page-top-title: Le Thanh Thoai
top-section-bg-text: Computer Science
home-subtitle: Le Thanh Thoai
copyright-text: '2025 &copy; <a href="https://thoailt.com">Le Thanh Thoai</a>'
